# services:
#   api-gateway:
#     build:
#       context: . 
#     container_name: api_gateway_service
#     ports:
#       - "3000:3000" 
#     depends_on:
#       - rabbitmq
#     environment:
#       - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
#     networks:
#       - api_gateway_network 
#     restart: unless-stopped

# networks:
#   api_gateway_network:
#     driver: bridge